extends:
  - standard
  - prettier
  - prettier/standard

plugins:
  - prettier
  - standard

rules:
  no-console: error

overrides:
  - files: '*.test.js'
    env:
      jest: true
  - files: '**/__utils__/**'
    env:
      jest: true
